namespace Pausalio.Shared.Localization
{
    public interface ILocalizationHelper
    {
        string LogoutSuccessful { get;  }
        string PaymentCreatedSuccessfully { get; }
        string PaymentUpdatedSuccessfully { get; }
        string PaymentDeletedSuccessfully { get; }
        string InvalidPaymentType { get; }
        string EntityIdRequired { get; }
        string PaymentNotFound { get; }
        string InvoiceAlreadyPaid { get; }
        string PaymentExceedsRemainingAmount { get; }
        string TaxObligationAlreadyPaid { get; }
        string TaxObligationMustBePaidInFull {  get; }
        string ExpenseAlreadyPaid { get; }
        string ExpenseMustBePaidInFull { get; }
        string InvoiceItemUnitPriceGreaterThanZero { get; }
        string CannotDeletePaidInvoice {  get; }
        string CannotModifyPaidInvoice {  get; }
        string InvalidInvoiceItemValues { get; }
        string InvoiceMustHaveItems { get; }
        string InvoiceDeletedSuccessfully { get; }
        string InvoiceUpdatedSuccessfully { get; }
        string InvoiceCreatedSuccessfully { get; }
        string InvoiceNotFound { get; }
        string IBANRequiredForForeignCurrency {  get; }
        string SWIFTRequiredForForeignCurrency { get; }
        string CountrySerbiaNotFound { get; }
        string ClientEmailAlreadyExists { get; }
        string CannotDeletePaidObligation {  get; }
        string CannotModifyPaidObligation {  get; }
        string ObligationAlreadyExistsForMonth {  get; }
        string ObligationsAlreadyExistForYear {  get; }
        string InvalidDueDay {  get; }
        string InvalidYear {  get; }
        string TaxObligationMarkedAsPaid {  get; }
        string TaxObligationDeletedSuccessfully {  get; }
        string TaxObligationUpdatedSuccessfully {  get; }
        string TaxObligationsGeneratedSuccessfully { get; }
        string TaxObligationCreatedSuccessfully {  get; }
        string TaxObligationNotFound {  get; }
        string CannotDeletePaidExpense {  get; }
        string CannotModifyPaidExpense {  get; }
        string AmountMustBePositive {  get; }
        string ExpenseArchivedSuccessfully {  get; }
        string ExpenseDeletedSuccessfully { get; }
        string ExpenseUpdatedSuccessfully {  get; }
        string ExpenseCreatedSuccessfully { get; }
        string ExpenseNotFound {  get; }
        string ForeignClientMustHaveCountry {  get; }
        string ClientWithPIBAlreadyExists { get; }
        string LegalEntityMustHavePIB {  get; }
        string ClientActivatedSuccessfully { get; }
        string ClientDeletedSuccessfully { get; }
        string ClientUpdatedSuccessfully { get; }
        string ClientCreatedSuccessfully { get; }
        string ClientNotFound {  get; }
        string CompanyWithPIBOrMBAlreadyExists { get; }
        string CompanyActivatedSuccessfully {  get; }
        string CompanyDeactivatedSuccessfully {  get; }
        string CompanyUpdatedSuccessfully {  get; }
        string CannotInviteOwner { get; }
        string CannotInviteAdmin { get; }
        string UserAlreadyAssistantInYourBusiness { get; }
        string InviteAlreadySentToThisUser { get; }
        string InviteAcceptedSuccessfully {  get; }
        string FailedToAddUserToBusiness {  get; }
        string AlreadyAssistantInBusiness {  get; }
        string Unauthorized {  get; }
        string InviteRemoved { get; }
        string InviteSent { get; }
        string FileUploadFailed {  get; }
        string FileUploadedSuccessfully {  get; }
        string UnsupportedFileType {  get; }
        string FileIsEmptyOrNotProvided { get; }
        string FileDeleteFailed { get; }
        string FileDeletedSuccessfully { get; }
        string UrlIsRequired { get; }
        string CountryCodeInvalidLength { get; }
        string CountryCodeRequired { get; }
        string CountryNameTooLong { get; }
        string CountryNameRequired { get; }
        string ActivityCodeDescriptionTooLong {  get; }
        string ActivityCodeDescriptionRequired { get; }
        string ActivityCodeTooLong {  get; }
        string ReminderDeletedSuccessfully {  get; }
        string ReminderMarkedCompleted {  get; }
        string ReminderUpdatedSuccessfully {  get; }
        string ReminderCreatedSuccessfully { get; }
        string ReminderNotFound {  get; }
        string ItemDeletedSuccessfully { get; }
        string ItemUpdatedSuccessfully {  get; }
        string ItemCreatedSuccessfully {  get; }
        string ItemNotFound {  get; }
        string DocumentDeletedSuccessfully { get; }
        string DocumentUpdatedSuccessfully {  get; }
        string DocumentCreatedSuccessfully { get; }
        string DocumentNotFound { get; }
        string CountryDeletedSuccessfully {  get; }
        string CountryUpdatedSuccessfully { get; }
        string CountryCreatedSuccessfully { get; }
        string CountryNotFound {  get; }
        string CityDeletedSuccessfully { get; }
        string CityUpdatedSuccessfully {  get; }
        string CityCreatedSuccessfully { get; }
        string CityNotFound {  get; }
        string BankAccountDeletedSuccessfully {  get; }
        string BankAccountUpdatedSuccessfully {  get; }
        string BankAccountCreatedSuccessfully { get; }
        string BankAccountNotFound {  get; }
        string ActivityCodeAlreadyExists { get; }
        string ActivityCodeDeletedSuccessfully { get; }
        string ActivityCodeUpdatedSuccessfully {  get; }
        string ActivityCodeCreatedSuccessfully {  get; }
        string ActivityCodeNotFound { get; }
        string CityNameMaxLength { get; }
        string CityNameRequired { get; }
        string PostalCodeMaxLength { get; }
        string PostalCodeRequired { get; }
        string InvalidCompanyId { get; }
        string UserCompanyNotFound { get; }
        string InvalidPassword { get; }
        string LoginSuccessfull {  get; }
        string UserEmailNotProvided { get; }
        string InviteTokenAlreadyExists { get; }
        string InviteTokenCreateFail { get; }
        string InvalidCredentials { get; }
        string EmailNotVerified { get; }
        string UserInactive { get; }
        string PasswordRegex { get; }
        string Register {  get; }
        string InviteTokenFooter { get; }
        string InviteTokenPageMessage { get; }
        string InviteTokenTitle { get; }
        string InviteTokenPageTitle { get; }
        string BusinesProfileNotFound { get; }
        string InviteTokenDismatch {  get; }
        string InviteTokenDoesNotExist { get; }
        string CompanyAlreadyExists { get; }
        string UserAlreadyExists { get; }
        string RegistrationFailed { get; }
        string ConfirmEmail { get; }
        string InvalidRequest { get; }
        string UserNotFound { get; }
        string InvalidOrExpiredToken { get; }
        string EmailVerifyGreeting { get; }
        string EmailVerifyText { get; }
        string EmailVerifyButton { get; }
        string EmailVerifyFallback { get; }
        string EmailVerifyFooter { get; }
        string VerificationSuccessTitle { get; }
        string VerificationSuccessHeading { get; }
        string VerificationSuccessMessage { get; }
        string GoToLogin { get; }
        string VerificationErrorTitle { get; }
        string VerificationErrorHeading { get; }
        string ResendVerificationEmail { get; }
        string GoToHome { get; }
        string EmailAlreadyVerified { get; }
        string VerificationEmailResent { get; }
        string RegistrationSuccessful { get; }
        string EmailVerifiedSuccessfully { get; }
        string EmailVerify { get; }
        string InviteTokenRequired { get; }
        string ExpiresAtFuture {  get; }
        string BusinessProfileIdInvalid { get; }
        string ClientCountryInvalid { get; }
        string ActivityCodeRequired { get; }
        string BankNameRequired { get; }
        string AccountNumberRequired { get; }
        string UnknownCurrency {  get; }
        string InvalidIBAN { get; }
        string InvalidSWIFT { get; }
        string BankNameMaxLength { get; }
        string AccountNumberLength { get; }
        string BusinessNameRequired { get; }
        string BusinessNameMaxLength { get; }
        string PIBRequired { get; }
        string PIBLength { get; }
        string MBLength { get; }
        string ActivityCodeMaxLength { get; }
        string CityRequired { get; }
        string CityMaxLength { get; }
        string AddressRequired { get; }
        string AddressMaxLength { get; }
        string EmailRequired { get; }
        string EmailInvalid { get; }
        string EmailMaxLength { get; }
        string PhoneInvalid { get; }
        string PhoneMaxLength { get; }
        string WebsiteInvalid { get; }
        string WebsiteMaxLength { get; }
        string CompanyLogoMaxLength { get; }
        string ClientNameRequired { get; }
        string ClientNameMaxLength { get; }
        string ClientPIBLength { get; }
        string ClientMBLength { get; }
        string ClientAddressRequired { get; }
        string ClientAddressMaxLength { get; }
        string ClientCityRequired { get; }
        string ClientCityMaxLength { get; }
        string ClientEmailRequired { get; }
        string ClientEmailInvalid { get; }
        string ClientEmailMaxLength { get; }
        string ClientPhoneInvalid { get; }
        string ClientPhoneMaxLength { get; }
        string ClientCountryMaxLength { get; }
        string DocumentNumberRequired { get; }
        string DocumentNumberMaxLength { get; }
        string DocumentFilePathRequired { get; }
        string DocumentFilePathMaxLength { get; }
        string ExpenseNameRequired { get; }
        string ExpenseNameMaxLength { get; }
        string ExpenseAmountGreaterThanZero { get; }
        string ExpenseStatusInvalid { get; }
        string InvoiceItemInvoiceIdRequired { get; }

        string InvoiceItemNameRequired { get; }
        string InvoiceItemNameMaxLength { get; }

        string InvoiceItemDescriptionMaxLength { get; }

        string InvoiceItemQuantityGreaterThanZero { get; }

        string InvoiceItemUnitPriceMinZero { get; }
        string InvoiceClientIdRequired { get; }

        string InvoiceDueDateNotInPast { get; }

        string InvoiceExchangeRateGreaterThanZero { get; }

        string InvoiceItemsRequired { get; }
        string ItemNameRequired { get; }
        string ItemNameMaxLength { get; }

        string ItemDescriptionMaxLength { get; }

        string ItemUnitPriceNonNegative { get; }
        string PaymentTypeUnknown { get; }
        string PaymentEntityIdRequired { get; }
        string PaymentAmountGreaterThanZero { get; }
        string PaymentUnknownCurrency { get; }
        string PaymentExchangeRateGreaterThanZero { get; }
        string PaymentReferenceMaxLength { get; }
        string PaymentDescriptionMaxLength { get; }
        string ReminderTitleRequired { get; }
        string ReminderTitleMaxLength { get; }
        string ReminderDescriptionMaxLength { get; }
        string ReminderTypeUnknown { get; }
        string ReminderDueDateInPast { get; }
        string TaxDueDateInPast { get; }
        string TaxTypeUnknown { get; }
        string TaxStatusUnknown { get; }
        string TaxTotalAmountGreaterThanZero { get; }

        string UserIdRequired { get; }
        string BusinessProfileIdRequired { get; }
        string UserBusinessRoleRequired { get; }
        string UserFirstNameRequired { get; }
        string UserFirstNameMaxLength { get; }
        string UserLastNameRequired { get; }
        string UserLastNameMaxLength { get; }
        string UserEmailRequired { get; }
        string UserEmailInvalid { get; }
        string UserEmailMaxLength { get; }
        string UserPasswordRequired { get; }
        string UserPasswordMaxLength { get; }
        string UserProfilePictureMaxLength { get; }
        string UserPhoneInvalid { get; }
        string UserPhoneMaxLength { get; }
        string UserCityMaxLength { get; }
        string UserAddressMaxLength { get; }
        string ServerError { get; }
        string UserProfileCreationFailed { get; }
    }
}
